generator:
  class: sfDoctrineGenerator
  param:
    model_class:           photos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          photos
    with_doctrine_route:   true
    actions_base_class:    sfActions
    config:
      actions: ~
      fields:  ~
      list:
        title: Les photos !
        layout: stacked
        display: [is_default,gallery,picpath]
        params:  |
          %%is_default%% <small>%%gallery%%</small> %%title%% <img x-image-id="%%photo_id%%" title="%%title%%" src="%%full_picpath_default%%"/>
        batch_actions:
          _delete:  ~
          rotate90:  ~
          rotate180:  ~
          rotate270:  ~
          blackAndWhite:
            label:  Black And White
          flipH:
            label:  Flip Horizontale
          flipV:
            label:  Flip Verticale
          colorize:  ~
          filigrane:  ~
          brightness:  ~
        object_actions:
          _edit:  ~
          _delete:  ~
          cancelLastAction:  ~
      filter:
        class: false
      form:
        class : PluginBackendPhotosForm
      edit:    ~
      new:     ~
